name: Build and Deploy Microservices to Azure

on:
  pull_request:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push patients-service
        run: |
          docker build -t $REGISTRY/patients-service ./services/patients-service
          docker push $REGISTRY/patients-service

      - name: Build and push symptoms-service
        run: |
          docker build -t $REGISTRY/symptoms-service ./services/symptoms-service
          docker push $REGISTRY/symptoms-service

      - name: Build and push vue-symptom-app
        run: |
          docker build --build-arg VITE_PATIENTS_SERVICE_URL=https://patients.example.com \
                       --build-arg VITE_SYMPTOMS_SERVICE_URL=https://symptoms.example.com \
                       -t $REGISTRY/vue-symptom-app ./client/vue-symptom-app
          docker push $REGISTRY/vue-symptom-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (patients-service)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_PATIENTS }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/patients-service

      - name: Deploy to Azure Web App (symptoms-service)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_SYMPTOMS }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/symptoms-service

      - name: Deploy to Azure Web App (vue-symptom-app)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}
          images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/vue-symptom-app